### ISSUE TITLE
How best to modularize snakemake workflows

### ISSUE THREAD

**Issue by SilasK** [snakemake-workflows/docs#17]
I'm developing [metagenome atlas](https://github.com/metagenome-atlas/atlas) a snakemake pipeline which for metagenomics which get s you all the steps from QC, assembly, binning, genome prediction, and annotation. 
I make a click wrapper to get users started in three commands.

Now I'm planning how to maintain this pipeline and thinking I should modularize it to be able to update and test parts

I read the snakemake docs about modularisation. 
- The first step Is definitively to make wrappers. 
- I thought, I should also create a sub workflows (e.g. QC/ assembly) and contribute them to snakemake-workflows project. 

Now my question is how I do it the best way so that the sub-workflows can work as stand-alone workflows but also as part of metagnome atlas?

**Comment by alienzj** [comment]
@SilasK I also have this idea, maybe we can work together.

**Comment by SilasK** [comment]
Great! Looking forward to collaborating with you @alienzj. Could you, please, contact me by mail, which you find on my personal webpage. 

I also saw that snakemake has in fact a new way to make deployable sub-workflows.

**Comment by dlaehnemann** [comment]
From your comments, I assume you are aware of the whole [modularization section in the Snakemake docs](https://snakemake.readthedocs.io/en/latest/snakefiles/modularization.html). In addition, the section on modules there links to [the docs page that describes "Using and combining pre-exising workflows"](https://snakemake.readthedocs.io/en/latest/snakefiles/deployment.html#using-and-combining-pre-exising-workflows). Also, further things were added there, since your last post. And especially have a look at using [the snakemake workflow template](https://github.com/snakemake-workflows/snakemake-workflow-template), which is very easy via [the "Use this template" button](https://github.com/snakemake-workflows/snakemake-workflow-template/generate).

I hope you have already gotten going and these links maybe provide some more useful infos. So I'll close the issue for now. But please do feel free to reopen this issue if you want to discuss this further!
